In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('ecommerce_messy_dataset.csv')

In [ ]:
df

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,NaN,4003.06,3.0,Cash
1,ORD10001,2022-03-03,CUST1761,Male,25.0,kolkata,Clothing,Lipstick,3033.43,2.0,NaN
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,NaN,Lipstick,589.88,3.0,Cash
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash
4,NaN,2023-05-04,CUST1532,Female,39.0,kolkata,Beauty,Dress,376.42,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5195,ORD10469,2023-01-23,CUST1172,M,34.0,Hyderabad,NaN,Dress,401.43,5.0,UPI
5196,ORD13297,2022-02-26,CUST1554,NaN,19.0,Hyderabad,NaN,Headphones,2897.86,5.0,Debit Card
5197,ORD14756,2023-09-12,CUST1566,M,55.0,NaN,Home,Laptop,2156.39,1.0,NaN
5198,ORD13192,2022-03-09,CUST1019,NaN,18.0,Bangalore,Electronics,Headphones,4952.09,5.0,Debit Card
5199,ORD13246,2024-05-28,CUST1298,Other,28.0,Delhi,Clothing,Laptop,3566.92,3.0,Credit Card

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5084 non-null   object
 1   Order_Date        4957 non-null   object
 2   Customer_ID       5140 non-null   object
 3   Gender            4311 non-null   object
 4   Age               5077 non-null   float64
 5   City              4567 non-null   object
 6   Product_Category  4316 non-null   object
 7   Product_Name      4497 non-null   object
 8   Price             5051 non-null   float64
 9   Quantity          4318 non-null   float64
 10  Payment_Method    4192 non-null   object
dtypes: float64(3), object(8)
memory usage: 447.0+ KB

In [ ]:
df.isnull().sum()

Order_ID             116
Order_Date           243
Customer_ID           60
Gender               889
Age                  123
City                 633
Product_Category     884
Product_Name         703
Price                149
Quantity             882
Payment_Method      1008
dtype: int64

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.describe()

               Age        Price     Quantity
count  4882.000000  4856.000000  4154.000000
mean     38.392052  2560.831512     3.001444
std      11.963644  1418.015862     1.429623
min      18.000000   100.060000     1.000000
25%      28.000000  1337.650000     2.000000
50%      38.000000  2579.715000     3.000000
75%      49.000000  3786.855000     4.000000
max      59.000000  4999.260000     5.000000

In [ ]:
df=df.dropna(subset=['Order_ID'])

In [ ]:
df.isnull().sum()

Order_ID              0
Order_Date          228
Customer_ID          57
Gender              838
Age                 118
City                593
Product_Category    838
Product_Name        666
Price               142
Quantity            828
Payment_Method      952
dtype: int64

In [ ]:
#Replace unknown methods
categorical=['Gender','City','Product_Category','Product_Name','Payment_Method']

In [ ]:
df[categorical]=df[categorical].fillna("Unknown")

In [ ]:
df.isnull().sum()

Order_ID              0
Order_Date          228
Customer_ID          57
Gender                0
Age                 118
City                  0
Product_Category      0
Product_Name          0
Price               142
Quantity            828
Payment_Method        0
dtype: int64

In [ ]:
df

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,Unknown,4003.06,3.0,Cash
1,ORD10001,2022-03-03,CUST1761,Male,25.0,kolkata,Clothing,Lipstick,3033.43,2.0,Unknown
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,Unknown,Lipstick,589.88,3.0,Cash
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash
5,ORD10005,2022-09-18,CUST1266,Other,47.0,Unknown,Beauty,Dress,1140.46,4.0,Unknown
...,...,...,...,...,...,...,...,...,...,...,...
4995,ORD14995,2024-03-06,CUST1174,M,52.0,kolkata,Clothing,Lipstick,3742.56,5.0,UPI
4996,ORD14996,2023-02-04,CUST1061,M,44.0,Bangalore,Sports,Shirt,1009.46,4.0,Unknown
4997,ORD14997,2023-02-12,CUST1759,Male,43.0,Mumbai,Home,Dress,2138.74,2.0,Unknown
4998,ORD14998,2023-07-19,CUST1144,Other,43.0,Bangalore,Beauty,Lipstick,545.11,3.0,Cash
4999,ORD14999,2022-01-14,CUST1073,Male,50.0,kolkata,Sports,Laptop,1380.31,NaN,Credit Card

In [ ]:
num=['Age','Price','Quantity']

In [ ]:
for col in num:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)
    print(f"Filled {col} with median: {median_val}")

Filled Age with median: 38.0
Filled Price with median: 2577.37
Filled Quantity with median: 3.0

In [ ]:
df.isnull().sum()

Order_ID              0
Order_Date          228
Customer_ID          57
Gender                0
Age                   0
City                  0
Product_Category      0
Product_Name          0
Price                 0
Quantity              0
Payment_Method        0
dtype: int64

In [ ]:
df=df.dropna(subset=['Customer_ID'])

In [ ]:
df["Gender"].unique()

array(['Female', 'Male', 'Other', 'Unknown'], dtype=object)

In [ ]:
df['Gender']=df['Gender'].replace({'M':'Male','F':'Female'})

/tmp/ipykernel_3992/3221419951.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender']=df['Gender'].replace({'M':'Male','F':'Female'})

In [ ]:
df

0       Female
1         Male
2        Other
3        Other
5        Other
         ...
4995      Male
4996      Male
4997      Male
4998     Other
4999      Male
Name: Gender, Length: 4834, dtype: object

In [ ]:
df['City'].unique()

array(['Delhi', 'kolkata', 'Mumbai', 'Hyderabad', 'Unknown', 'Kolkata',
       'Bangalore', 'Chennai'], dtype=object)

In [ ]:
#replace Kolkatta to Kolkata
df['City']=df['City'].replace({'Kolkatta':'Kolkata'})

/tmp/ipykernel_3992/1903670181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City']=df['City'].replace({'Kolkatta':'Kolkata'})

In [ ]:
df['City'].unique()

array(['Delhi', 'Kolkata', 'Mumbai', 'Hyderabad', 'Unknown', 'Bangalore',
       'Chennai'], dtype=object)

In [ ]:
#correlation error
df['Order_Date']=pd.to_datetime(df['Order_Date'])

/tmp/ipykernel_3992/3575969854.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date']=pd.to_datetime(df['Order_Date'])

In [ ]:
df['Order_Date'].fillna(method='ffill',inplace=True)

/tmp/ipykernel_3992/4168281717.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_Date'].fillna(method='ffill',inplace=True)
/tmp/ipykernel_3992/4168281717.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order_Date'].fillna(method='ffill',inplace=True)
/tmp/ipykernel_3992/4168281717.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date'].fillna(method='ffill',inplace=True)

In [ ]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Gender              0
Age                 0
City                0
Product_Category    0
Product_Name        0
Price               0
Quantity            0
Payment_Method      0
dtype: int64

In [ ]:
df['Total']=df['Price']*df['Quantity']

/tmp/ipykernel_3992/1737798978.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Total']=df['Price']*df['Quantity']

In [ ]:
df.head()

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method,Total
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,Unknown,4003.06,3.0,Cash,12009.18
1,ORD10001,2022-03-03,CUST1761,Male,25.0,Kolkata,Clothing,Lipstick,3033.43,2.0,Unknown,6066.86
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,Unknown,Lipstick,589.88,3.0,Cash,1769.64
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash,5205.51
5,ORD10005,2022-09-18,CUST1266,Other,47.0,Unknown,Beauty,Dress,1140.46,4.0,Unknown,4561.84